---
- hosts: lab
  become: true
  vars:
    packages: 
      - postfix
      - dovecot
      - squirrelmail
      - httpd
  tasks: 
- name:   Instalar paquetes "{{ packages }}"
  yum:  
    name: "{{ packages }}"
  

