---
- hosts: lab
  become: true
  vars:
    packages: 
      - postfix
      - dovecot
      - httpd
    interfaces: all
  tasks: 
  - name:   Instalar paquetes "{{ packages }}"
    yum:  
      name: "{{ packages }}"
  - name: COnfiguracion de Main.cf
    template:
      src: main.cf.j2
      dest: /etc/postfix/main.cf
      

