---
- hosts: lab
  become: true
  vars:
    packages: 
      - postfix
      - dovecot
      - httpd
  tasks: 
  - name:   Instalar paquetes "{{ packages }}"
    yum:  
      name: "{{ packages }}"
  

